(cl:defpackage beginner_tutorials-srv
  (:use )
  (:export
   "ADDTHREEINTS"
   "<ADDTHREEINTS-REQUEST>"
   "ADDTHREEINTS-REQUEST"
   "<ADDTHREEINTS-RESPONSE>"
   "ADDTHREEINTS-RESPONSE"
   "ADDTWOINTS"
   "<ADDTWOINTS-REQUEST>"
   "ADDTWOINTS-REQUEST"
   "<ADDTWOINTS-RESPONSE>"
   "ADDTWOINTS-RESPONSE"
  ))

